[package]
name = "llm-chain-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llm-chain = "0.13.0"
llm-chain-llama = "0.13.0"
tokio = { version = "1.35.1", features = ["full"] }
